
#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: false
theme: "just-the-docs"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]


#github:
#  is_project_page: false
